on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
      pull-requests: write
    steps:
      - name: ⬇️ Git Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: ⚙️ Install pixi env
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.58.0
          activate-environment: true

      - name: Additional Environment Initialization
        run: task init

      - name: 🧪 Validate project
        run: task lint test

      - id: release
        name: 📃 Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple

      - if: ${{ steps.release.outputs.release_created }}
        run: |
          echo 'Released Version: ${{ steps.release.outputs.version }}'
