on:
  workflow_call:
    inputs:
      release-version:
        type: string
        required: true
      release-tag:
        type: string
        required: true

env:
  CI: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    steps:
      - name: ⬇️ Git Checkout
        uses: actions/checkout@v5

      - name: ⚙️ Install pixi env
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.58.0
          activate-environment: true

      - name: 🚀 Publish release
        run: task publish
        env:
          RELEASE_VERSION: ${{ inputs.release-version }}
          RELEASE_TAG: ${{ inputs.release-tag }}
